# Generated by Django 5.0.1 on 2024-03-15 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0002_customerdetails_delete_puppy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetails',
            name='number',
            field=models.PositiveIntegerField(max_length=10),
        ),
    ]
