# Generated by Django 5.0.1 on 2024-03-15 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0004_puppydetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puppydetails',
            name='age',
            field=models.CharField(max_length=50),
        ),
    ]
